//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ULA.Quijano.ProcesoLegal.Resources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class General
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal General()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ULA.Quijano.ProcesoLegal.Resources.General", typeof(General).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string PAR_Plazo_Maximo_Auto
        {
            get
            {
                return ResourceManager.GetString("PAR_Plazo_Maximo_Auto", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 52.
        /// </summary>
        public static string PAR_Valor_Maximo_Auto
        {
            get
            {
                return ResourceManager.GetString("PAR_Valor_Maximo_Auto", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 51.
        /// </summary>
        public static string PAR_Valor_Minimo_Auto
        {
            get
            {
                return ResourceManager.GetString("PAR_Valor_Minimo_Auto", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        public static string PRO_Prestamo_Auto
        {
            get
            {
                return ResourceManager.GetString("PRO_Prestamo_Auto", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ClienteCentrico.
        /// </summary>
        public static string ProcesoClienteCentrico
        {
            get
            {
                return ResourceManager.GetString("ProcesoClienteCentrico", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SolicitudTarjetaCredito.
        /// </summary>
        public static string ProcesoTDC
        {
            get
            {
                return ResourceManager.GetString("ProcesoTDC", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Informacion del Solicitante.
        /// </summary>
        public static string TAB_InformacionSolicitante_TDC
        {
            get
            {
                return ResourceManager.GetString("TAB_InformacionSolicitante_TDC", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Solicitud.
        /// </summary>
        public static string TAB_Solicitud
        {
            get
            {
                return ResourceManager.GetString("TAB_Solicitud", resourceCulture);
            }
        }
    }
}
