//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
// 
#pragma warning disable 1591

namespace ULA.Quijano.ProcesoLegal.WsComunicacion {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WsComunicacionSoap", Namespace="http://tempuri.org/")]
    public partial class WsComunicacion : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback EnviarComunicacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnviarNotificacionServiciosLegalesOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnviarEnlaceServicioOperationCompleted;
        
        private System.Threading.SendOrPostCallback GenerarServicioLegalOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WsComunicacion() {
            this.Url = global::ULA.Quijano.ProcesoLegal.Properties.Settings.Default.ULA_Quijano_ProcesoLegal_WsComunicacion_WsComunicacion;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event EnviarComunicacionCompletedEventHandler EnviarComunicacionCompleted;
        
        /// <remarks/>
        public event EnviarNotificacionServiciosLegalesCompletedEventHandler EnviarNotificacionServiciosLegalesCompleted;
        
        /// <remarks/>
        public event EnviarEnlaceServicioCompletedEventHandler EnviarEnlaceServicioCompleted;
        
        /// <remarks/>
        public event GenerarServicioLegalCompletedEventHandler GenerarServicioLegalCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviarComunicacion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool EnviarComunicacion(string proceso, int incidente) {
            object[] results = this.Invoke("EnviarComunicacion", new object[] {
                        proceso,
                        incidente});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void EnviarComunicacionAsync(string proceso, int incidente) {
            this.EnviarComunicacionAsync(proceso, incidente, null);
        }
        
        /// <remarks/>
        public void EnviarComunicacionAsync(string proceso, int incidente, object userState) {
            if ((this.EnviarComunicacionOperationCompleted == null)) {
                this.EnviarComunicacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviarComunicacionOperationCompleted);
            }
            this.InvokeAsync("EnviarComunicacion", new object[] {
                        proceso,
                        incidente}, this.EnviarComunicacionOperationCompleted, userState);
        }
        
        private void OnEnviarComunicacionOperationCompleted(object arg) {
            if ((this.EnviarComunicacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviarComunicacionCompleted(this, new EnviarComunicacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviarNotificacionServiciosLegales", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool EnviarNotificacionServiciosLegales(string proceso, int incidente) {
            object[] results = this.Invoke("EnviarNotificacionServiciosLegales", new object[] {
                        proceso,
                        incidente});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void EnviarNotificacionServiciosLegalesAsync(string proceso, int incidente) {
            this.EnviarNotificacionServiciosLegalesAsync(proceso, incidente, null);
        }
        
        /// <remarks/>
        public void EnviarNotificacionServiciosLegalesAsync(string proceso, int incidente, object userState) {
            if ((this.EnviarNotificacionServiciosLegalesOperationCompleted == null)) {
                this.EnviarNotificacionServiciosLegalesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviarNotificacionServiciosLegalesOperationCompleted);
            }
            this.InvokeAsync("EnviarNotificacionServiciosLegales", new object[] {
                        proceso,
                        incidente}, this.EnviarNotificacionServiciosLegalesOperationCompleted, userState);
        }
        
        private void OnEnviarNotificacionServiciosLegalesOperationCompleted(object arg) {
            if ((this.EnviarNotificacionServiciosLegalesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviarNotificacionServiciosLegalesCompleted(this, new EnviarNotificacionServiciosLegalesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviarEnlaceServicio", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool EnviarEnlaceServicio(string proceso, int incidente) {
            object[] results = this.Invoke("EnviarEnlaceServicio", new object[] {
                        proceso,
                        incidente});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void EnviarEnlaceServicioAsync(string proceso, int incidente) {
            this.EnviarEnlaceServicioAsync(proceso, incidente, null);
        }
        
        /// <remarks/>
        public void EnviarEnlaceServicioAsync(string proceso, int incidente, object userState) {
            if ((this.EnviarEnlaceServicioOperationCompleted == null)) {
                this.EnviarEnlaceServicioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviarEnlaceServicioOperationCompleted);
            }
            this.InvokeAsync("EnviarEnlaceServicio", new object[] {
                        proceso,
                        incidente}, this.EnviarEnlaceServicioOperationCompleted, userState);
        }
        
        private void OnEnviarEnlaceServicioOperationCompleted(object arg) {
            if ((this.EnviarEnlaceServicioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviarEnlaceServicioCompleted(this, new EnviarEnlaceServicioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GenerarServicioLegal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool GenerarServicioLegal(string proceso, int incidente, string usuario) {
            object[] results = this.Invoke("GenerarServicioLegal", new object[] {
                        proceso,
                        incidente,
                        usuario});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GenerarServicioLegalAsync(string proceso, int incidente, string usuario) {
            this.GenerarServicioLegalAsync(proceso, incidente, usuario, null);
        }
        
        /// <remarks/>
        public void GenerarServicioLegalAsync(string proceso, int incidente, string usuario, object userState) {
            if ((this.GenerarServicioLegalOperationCompleted == null)) {
                this.GenerarServicioLegalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerarServicioLegalOperationCompleted);
            }
            this.InvokeAsync("GenerarServicioLegal", new object[] {
                        proceso,
                        incidente,
                        usuario}, this.GenerarServicioLegalOperationCompleted, userState);
        }
        
        private void OnGenerarServicioLegalOperationCompleted(object arg) {
            if ((this.GenerarServicioLegalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenerarServicioLegalCompleted(this, new GenerarServicioLegalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void EnviarComunicacionCompletedEventHandler(object sender, EnviarComunicacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnviarComunicacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnviarComunicacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void EnviarNotificacionServiciosLegalesCompletedEventHandler(object sender, EnviarNotificacionServiciosLegalesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnviarNotificacionServiciosLegalesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnviarNotificacionServiciosLegalesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void EnviarEnlaceServicioCompletedEventHandler(object sender, EnviarEnlaceServicioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnviarEnlaceServicioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnviarEnlaceServicioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GenerarServicioLegalCompletedEventHandler(object sender, GenerarServicioLegalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GenerarServicioLegalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GenerarServicioLegalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591