//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ULA.Quijano.Internet.Mensajeria {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Servicio", Namespace="http://schemas.datacontract.org/2004/07/ULA.Quijano.SendMails")]
    [System.SerializableAttribute()]
    public partial class Servicio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AsuntoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComentariosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComentariosResolucionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoResponsableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaSeguimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HorarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdAccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEntidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IncidenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreDeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreParaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreResponsableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PisoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenciasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResponsableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SociedadEntidadEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SolicitadoPorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SolicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TramiteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Accion {
            get {
                return this.AccionField;
            }
            set {
                if ((object.ReferenceEquals(this.AccionField, value) != true)) {
                    this.AccionField = value;
                    this.RaisePropertyChanged("Accion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Asunto {
            get {
                return this.AsuntoField;
            }
            set {
                if ((object.ReferenceEquals(this.AsuntoField, value) != true)) {
                    this.AsuntoField = value;
                    this.RaisePropertyChanged("Asunto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Calle {
            get {
                return this.CalleField;
            }
            set {
                if ((object.ReferenceEquals(this.CalleField, value) != true)) {
                    this.CalleField = value;
                    this.RaisePropertyChanged("Calle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comentarios {
            get {
                return this.ComentariosField;
            }
            set {
                if ((object.ReferenceEquals(this.ComentariosField, value) != true)) {
                    this.ComentariosField = value;
                    this.RaisePropertyChanged("Comentarios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ComentariosResolucion {
            get {
                return this.ComentariosResolucionField;
            }
            set {
                if ((object.ReferenceEquals(this.ComentariosResolucionField, value) != true)) {
                    this.ComentariosResolucionField = value;
                    this.RaisePropertyChanged("ComentariosResolucion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorreoResponsable {
            get {
                return this.CorreoResponsableField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoResponsableField, value) != true)) {
                    this.CorreoResponsableField = value;
                    this.RaisePropertyChanged("CorreoResponsable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Detalle {
            get {
                return this.DetalleField;
            }
            set {
                if ((object.ReferenceEquals(this.DetalleField, value) != true)) {
                    this.DetalleField = value;
                    this.RaisePropertyChanged("Detalle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaSeguimiento {
            get {
                return this.FechaSeguimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaSeguimientoField, value) != true)) {
                    this.FechaSeguimientoField = value;
                    this.RaisePropertyChanged("FechaSeguimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Horario {
            get {
                return this.HorarioField;
            }
            set {
                if ((object.ReferenceEquals(this.HorarioField, value) != true)) {
                    this.HorarioField = value;
                    this.RaisePropertyChanged("Horario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAccion {
            get {
                return this.IdAccionField;
            }
            set {
                if ((this.IdAccionField.Equals(value) != true)) {
                    this.IdAccionField = value;
                    this.RaisePropertyChanged("IdAccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEntidad {
            get {
                return this.IdEntidadField;
            }
            set {
                if ((this.IdEntidadField.Equals(value) != true)) {
                    this.IdEntidadField = value;
                    this.RaisePropertyChanged("IdEntidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Incidente {
            get {
                return this.IncidenteField;
            }
            set {
                if ((this.IncidenteField.Equals(value) != true)) {
                    this.IncidenteField = value;
                    this.RaisePropertyChanged("Incidente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreDe {
            get {
                return this.NombreDeField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreDeField, value) != true)) {
                    this.NombreDeField = value;
                    this.RaisePropertyChanged("NombreDe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreEstado {
            get {
                return this.NombreEstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreEstadoField, value) != true)) {
                    this.NombreEstadoField = value;
                    this.RaisePropertyChanged("NombreEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombrePara {
            get {
                return this.NombreParaField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreParaField, value) != true)) {
                    this.NombreParaField = value;
                    this.RaisePropertyChanged("NombrePara");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreResponsable {
            get {
                return this.NombreResponsableField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreResponsableField, value) != true)) {
                    this.NombreResponsableField = value;
                    this.RaisePropertyChanged("NombreResponsable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Piso {
            get {
                return this.PisoField;
            }
            set {
                if ((object.ReferenceEquals(this.PisoField, value) != true)) {
                    this.PisoField = value;
                    this.RaisePropertyChanged("Piso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Referencias {
            get {
                return this.ReferenciasField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenciasField, value) != true)) {
                    this.ReferenciasField = value;
                    this.RaisePropertyChanged("Referencias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Responsable {
            get {
                return this.ResponsableField;
            }
            set {
                if ((this.ResponsableField.Equals(value) != true)) {
                    this.ResponsableField = value;
                    this.RaisePropertyChanged("Responsable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SociedadEntidadEmpresa {
            get {
                return this.SociedadEntidadEmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.SociedadEntidadEmpresaField, value) != true)) {
                    this.SociedadEntidadEmpresaField = value;
                    this.RaisePropertyChanged("SociedadEntidadEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SolicitadoPor {
            get {
                return this.SolicitadoPorField;
            }
            set {
                if ((object.ReferenceEquals(this.SolicitadoPorField, value) != true)) {
                    this.SolicitadoPorField = value;
                    this.RaisePropertyChanged("SolicitadoPor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Solicitud {
            get {
                return this.SolicitudField;
            }
            set {
                if ((object.ReferenceEquals(this.SolicitudField, value) != true)) {
                    this.SolicitudField = value;
                    this.RaisePropertyChanged("Solicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tramite {
            get {
                return this.TramiteField;
            }
            set {
                if ((object.ReferenceEquals(this.TramiteField, value) != true)) {
                    this.TramiteField = value;
                    this.RaisePropertyChanged("Tramite");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstadoSolicitud", Namespace="http://schemas.datacontract.org/2004/07/ULA.Quijano.SendMails")]
    [System.SerializableAttribute()]
    public partial class EstadoSolicitud : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CompletarTareaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CompletarTarea {
            get {
                return this.CompletarTareaField;
            }
            set {
                if ((this.CompletarTareaField.Equals(value) != true)) {
                    this.CompletarTareaField = value;
                    this.RaisePropertyChanged("CompletarTarea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Mensajeria.IWcfMensajeria")]
    public interface IWcfMensajeria {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMensajeria/GetServicioByID", ReplyAction="http://tempuri.org/IWcfMensajeria/GetServicioByIDResponse")]
        ULA.Quijano.Internet.Mensajeria.Servicio GetServicioByID(int incidenteID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMensajeria/GetServicioByID", ReplyAction="http://tempuri.org/IWcfMensajeria/GetServicioByIDResponse")]
        System.Threading.Tasks.Task<ULA.Quijano.Internet.Mensajeria.Servicio> GetServicioByIDAsync(int incidenteID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMensajeria/ActualizarEstadoServicio", ReplyAction="http://tempuri.org/IWcfMensajeria/ActualizarEstadoServicioResponse")]
        bool ActualizarEstadoServicio(int incidenteID, string estado, string comentariosResolucion, string fechaSeguimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMensajeria/ActualizarEstadoServicio", ReplyAction="http://tempuri.org/IWcfMensajeria/ActualizarEstadoServicioResponse")]
        System.Threading.Tasks.Task<bool> ActualizarEstadoServicioAsync(int incidenteID, string estado, string comentariosResolucion, string fechaSeguimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMensajeria/GetEstadoSolicitud", ReplyAction="http://tempuri.org/IWcfMensajeria/GetEstadoSolicitudResponse")]
        System.Collections.Generic.List<ULA.Quijano.Internet.Mensajeria.EstadoSolicitud> GetEstadoSolicitud();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMensajeria/GetEstadoSolicitud", ReplyAction="http://tempuri.org/IWcfMensajeria/GetEstadoSolicitudResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ULA.Quijano.Internet.Mensajeria.EstadoSolicitud>> GetEstadoSolicitudAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWcfMensajeriaChannel : ULA.Quijano.Internet.Mensajeria.IWcfMensajeria, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WcfMensajeriaClient : System.ServiceModel.ClientBase<ULA.Quijano.Internet.Mensajeria.IWcfMensajeria>, ULA.Quijano.Internet.Mensajeria.IWcfMensajeria {
        
        public WcfMensajeriaClient() {
        }
        
        public WcfMensajeriaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WcfMensajeriaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfMensajeriaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfMensajeriaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ULA.Quijano.Internet.Mensajeria.Servicio GetServicioByID(int incidenteID) {
            return base.Channel.GetServicioByID(incidenteID);
        }
        
        public System.Threading.Tasks.Task<ULA.Quijano.Internet.Mensajeria.Servicio> GetServicioByIDAsync(int incidenteID) {
            return base.Channel.GetServicioByIDAsync(incidenteID);
        }
        
        public bool ActualizarEstadoServicio(int incidenteID, string estado, string comentariosResolucion, string fechaSeguimiento) {
            return base.Channel.ActualizarEstadoServicio(incidenteID, estado, comentariosResolucion, fechaSeguimiento);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarEstadoServicioAsync(int incidenteID, string estado, string comentariosResolucion, string fechaSeguimiento) {
            return base.Channel.ActualizarEstadoServicioAsync(incidenteID, estado, comentariosResolucion, fechaSeguimiento);
        }
        
        public System.Collections.Generic.List<ULA.Quijano.Internet.Mensajeria.EstadoSolicitud> GetEstadoSolicitud() {
            return base.Channel.GetEstadoSolicitud();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ULA.Quijano.Internet.Mensajeria.EstadoSolicitud>> GetEstadoSolicitudAsync() {
            return base.Channel.GetEstadoSolicitudAsync();
        }
    }
}
